version: '3.7'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER:?err}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:?err}
    ports:
      - 27017:27017
    volumes:
      - ~/mongo/data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER:?err}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD:?err}
  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379
