version: '3.7'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER:?err}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:?err}
    ports:
      - 27017:27017
    volumes:
      - ~/mongo/data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER:?err}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD:?err}
  zombie-service:
    image: 'docker.pkg.github.com/sertomviz/node-task-01/zombie-service:${VERSION_TAG:?err}'
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - '9001:9001'
    environment:
      ZOMBIE_ITEMS_EXCHANGE_URL: ${ZOMBIE_ITEMS_EXCHANGE_URL:?err}
      CURRENCY_EXCHANGE_URL: ${CURRENCY_EXCHANGE_URL:?err}
      MONGODB_URL: ${MONGODB_URL:?err}
      MONGODB_USER: ${MONGODB_USER:?err}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD:?err}
      API_PORT: '${API_PORT:?er\r}'
      REDIS_HOST: '${REDIS_HOST:?err}'
      REDIS_PORT: '${REDIS_PORT:?err}'
  redis:
    image: redis
    ports:
      - 6379:6379
